# Workflow name
name: Deploy Docs

# Allow this workflow to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Workflow triggers - What triggers it to run
on:
  # Only run the workflow if the documentation is modified to avoid unnecessary runs
  push:
    paths:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Workflow actions
jobs:
  # Build the site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download the Git repo
        uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v4
        with:
          path: ./docs
          package-manager: pnpm@latest
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: gh-pages
          path: ./docs/dist

  # Publish the site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Push the built documentation to the `gh-pages` branch
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
