name: Deploy Documentation

on:
  push:
    branches:
      - main

env:
  DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        run: cargo install mdbook --locked

      - name: Build mdBook
        run: mdbook build docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./docs/book
          publish_branch: gh-pages