# Workflow name
name: Deploy Documentation

# Workflow triggers - What triggers it to run
on:
  push:
    # Only run the workflow if the documentation is modified to avoid unnecessary runs
    paths:
      - 'docs/**'

    # Allows you to run this workflow manually from the Actions tab on GitHub.
    workflow_dispatch:

# Workflow actions
jobs:
  # Build the site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v4
        with:
          path: ./docs
          package-manager: pnpm@latest

  # Publish the site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Push the built documentation to the `gh-pages` branch
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
