name: Format All Nix Code

# When to run the workflow
on:
  # When code is pushed to `main` branch
  push:
    branches: [main]

  # When a PR is opened, pushed to or reopened and it's targeting the `main` branch
  pull_request:
    branches: [main]

  # Manually trigger this workflow from the Github Actions tab
  workflow_dispatch:

# Workflow actions
jobs:
  # Format all Nix files with Alejandra
  format:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Nix and run the formatter (Alejandra)
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Run Alejandra (Formatter)
        run: nix fmt .
